# Generated by Django 5.2.7 on 2026-02-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='primeiro_acesso',
            field=models.BooleanField(default=True),
        ),
    ]