# Generated by Django 5.2.7 on 2026-02-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usuario_primeiro_acesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(default='Bem-vindo ao GAIA - Suas Credenciais', max_length=200)),
                ('mensagem', models.TextField(default='Olá {nome},\n\nSeu cadastro no sistema GAIA foi realizado com sucesso.\n\nSuas credenciais de acesso são:\nLogin (CPF): {cpf}\nSenha Temporária: {senha}\n\nPor favor, altere sua senha no primeiro acesso.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de E-mail',
                'verbose_name_plural': 'Configurações de E-mail',
            },
        ),
    ]