# Generated by Django 5.2.7 on 2026-02-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_configuracaoemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoemail',
            name='mensagem',
            field=models.TextField(default='Olá {nome},\n\n    Seu cadastro no sistema GAIA foi realizado com sucesso.\n\n    Suas credenciais de acesso são:\n    Login (CPF): {cpf}\n    Senha Temporária: {senha}\n\n    Por favor, altere sua senha no primeiro acesso.'),
        ),
    ]
