# Generated by Django 5.2.7 on 2026-02-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_configuracaoemail_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
