# Generated by Django 5.2.7 on 2026-02-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_configuracaoemail_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoemail',
            name='assunto_mudanca_email',
            field=models.CharField(blank=True, default='GAIA - Seu E-mail foi Atualizado', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracaoemail',
            name='assunto_mudanca_login',
            field=models.CharField(blank=True, default='GAIA - Seu Login foi Atualizado', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracaoemail',
            name='mensagem_mudanca_email',
            field=models.TextField(blank=True, default='Olá {nome},\n\nConfirmamos que o e-mail da sua conta no sistema GAIA foi atualizado com sucesso.\n\nSeu novo e-mail de acesso é:\n{novo_email}\n\nSe você não realizou esta alteração, entre em contato imediatamente com nosso suporte.\n\nAtt,\nEquipe GAIA'),
        ),
        migrations.AddField(
            model_name='configuracaoemail',
            name='mensagem_mudanca_login',
            field=models.TextField(blank=True, default='Olá {nome},\n\nInformamos que o login para acessar o sistema GAIA foi atualizado.\n\nSeu novo login é:\n{novo_login}\n\nSe você não realizou esta alteração, entre em contato imediatamente com nosso suporte.\n\nAtt,\nEquipe GAIA'),
        ),
        migrations.AlterField(
            model_name='configuracaoemail',
            name='mensagem',
            field=models.TextField(default='Olá {nome},\n\n    Seu cadastro no sistema GAIA foi realizado com sucesso.\n\n    Suas credenciais de acesso são:\n    Login: Seu CPF\n    Senha Temporária: {senha}\n\n    Por favor, altere sua senha no primeiro acesso.\n                                \n    Em caso de dúvidas, entre em contato com nosso suporte (46) 999XX-XXXX.'),
        ),
    ]
