# Generated by Django 5.2.7 on 2026-02-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_configuracaoemail_notificacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoemail',
            name='mensagem',
            field=models.TextField(default='Olá {nome},\n\n    Seu cadastro no sistema GAIA foi realizado com sucesso.\n\n    Suas credenciais de acesso são:\n    Login (CPF/CNPJ): {cpf}\n    Senha Temporária: {senha}\n\n    Por favor, altere sua senha no primeiro acesso.\n                                \n    Em caso de dúvidas, entre em contato com nosso suporte (46) 999XX-XXXX.'),
        ),
    ]
