# Generated by Django 5.2.7 on 2026-02-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_configuracaoemail_assunto_mudanca_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoemail',
            name='assunto_mudanca_email',
        ),
        migrations.RemoveField(
            model_name='configuracaoemail',
            name='assunto_mudanca_login',
        ),
        migrations.RemoveField(
            model_name='configuracaoemail',
            name='mensagem_mudanca_email',
        ),
        migrations.RemoveField(
            model_name='configuracaoemail',
            name='mensagem_mudanca_login',
        ),
        migrations.AlterField(
            model_name='configuracaoemail',
            name='mensagem',
            field=models.TextField(default='Olá {nome},\n\nSeu cadastro no sistema GAIA foi realizado com sucesso.\nLogin: Seu CPF\nSua senha temporária é:\n{senha}\n\nPor favor, altere sua senha no primeiro acesso.\n\nEm caso de dúvidas, entre em contato com nosso suporte.'),
        ),
    ]
