# Generated by Django 5.2.7 on 2026-03-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_configuracaoemail_assunto_mudanca_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoemail',
            name='mensagem',
            field=models.TextField(default='Olá {nome},\n\nSeu cadastro no sistema GAIA foi realizado com sucesso.\n\nLogin: Seu {tipo_documento}\nSua senha temporária é:\n{senha}\n\nPor favor, altere sua senha no primeiro acesso.\n\nEm caso de dúvidas, entre em contato com nosso suporte pelo numero (46)99999-9999 ou pelo email labsolos@gmail.com'),
        ),
        migrations.CreateModel(
            name='CaptchaChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('challenge_token', models.CharField(max_length=64, unique=True)),
                ('challenge_key', models.CharField(max_length=10)),
                ('correct_answer', models.CharField(max_length=10)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_solved', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['challenge_token'], name='authenticat_challen_e5e695_idx'), models.Index(fields=['expires_at'], name='authenticat_expires_2646c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['identifier', 'timestamp'], name='authenticat_identif_68f74c_idx'), models.Index(fields=['ip_address', 'timestamp'], name='authenticat_ip_addr_95756c_idx')],
            },
        ),
    ]
