import { gray, white, lightGray, black, green } from "../../config/colors.js";

export const styles = {
  container: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    backgroundColor: gray,
    color: black,
    fontFamily: "Poppins, sans-serif",
  },
  box: {
    backgroundColor: white,
    padding: "30px",
    borderRadius: "8px",
    textAlign: "center",
    width: "100%",
    maxWidth: "400px",
    boxShadow: "0 5px 10px 0 rgba(0, 0, 0, 0.10)",
  },
  mobileBox: {
    boxShadow: "none",
    borderRadius: "0",
    backgroundColor: "transparent",
  },
  button: {
    width: "100%",
    padding: "10px",
    backgroundColor: green,
    color: white,
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontWeight: 600,
    fontFamily: "Poppins, sans-serif",
    marginTop: "10px",
  },
  link: {
    display: "block",
    marginTop: "15px",
    color: lightGray,
    cursor: "pointer",
    fontSize: "0.9rem",
    fontFamily: "Poppins, sans-serif",
    textDecoration: "underline",
  },
  message: {
    marginTop: "16px",
    padding: "10px",
    borderRadius: "4px",
    fontWeight: 600,
    fontSize: "0.9rem",
    fontFamily: "Poppins, sans-serif",
    whiteSpace: "pre-wrap",
    textAlign: "left",
  },
  messageSuccess: {
    color: "#155724",
    backgroundColor: "#d4edda",
    border: "1px solid #c3e6cb",
  },
  messageError: {
    color: "#721c24",
    backgroundColor: "#f8d7da",
    border: "1px solid #f5c6cb",
  },
};
