# Generated by Django 5.2.7 on 2025-10-28 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('pais', models.CharField(default='Brasil', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
                ('numero_registro', models.IntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
            },
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_amostra', models.IntegerField()),
                ('data_coleta', models.DateField()),
                ('arquivo_pdf', models.FileField(upload_to='laudos/pdf/')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_amostra', models.IntegerField()),
                ('data_coleta', models.DateField()),
                ('descricao', models.TextField(blank=True)),
                ('area_total', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('profundidade', models.FloatField(blank=True, null=True)),
                ('fosforo', models.FloatField(blank=True, null=True)),
                ('potassio', models.FloatField(blank=True, null=True)),
                ('materia_organica', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('aluminio', models.FloatField(blank=True, null=True)),
                ('h_al', models.FloatField(blank=True, null=True)),
                ('calcio', models.FloatField(blank=True, null=True)),
                ('magnesio', models.FloatField(blank=True, null=True)),
                ('cobre', models.FloatField(blank=True, null=True)),
                ('ferro', models.FloatField(blank=True, null=True)),
                ('manganes', models.FloatField(blank=True, null=True)),
                ('zinco', models.FloatField(blank=True, null=True)),
                ('soma_bases', models.FloatField(blank=True, null=True)),
                ('ctc', models.FloatField(blank=True, null=True)),
                ('v_percent', models.FloatField(blank=True, null=True)),
                ('saturacao_aluminio', models.FloatField(blank=True, null=True)),
                ('ctc_efetiva', models.FloatField(blank=True, null=True)),
                ('argila', models.FloatField(blank=True, null=True)),
                ('silte', models.FloatField(blank=True, null=True)),
                ('areia', models.FloatField(blank=True, null=True)),
                ('classificacao', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.propriedade')),
            ],
        ),
    ]
