# Generated by Django 5.2.7 on 2026-01-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
    ]
