# Generated by Django 5.2.7 on 2026-01-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_remove_empresa_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='propriedade',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='propriedade',
            old_name='numero_registro',
            new_name='registration_number',
        ),
    ]
