# Generated by Django 5.2.7 on 2026-01-13 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_rename_nome_empresa_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriedade',
            name='proprietario',
        ),
        migrations.AddField(
            model_name='propriedade',
            name='proprietario_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.empresa'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='proprietario_pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.person'),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.person'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='cpf_cnpj',
            field=models.CharField(default=1, max_length=14, verbose_name='CPF/CNPJ'),
            preserve_default=False,
        ),
    ]
