# Generated by Django 5.2.7 on 2026-01-14 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_remove_propriedade_proprietario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriedade',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='person',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report.endereco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propriedade',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report.endereco'),
            preserve_default=False,
        ),
    ]
