# Generated by Django 5.2.7 on 2026-01-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_remove_propriedade_localizacao_person_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriedade',
            name='cpf_cnpj',
        ),
    ]
