# Generated by Django 5.2.7 on 2026-01-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_remove_propriedade_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='localizacao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
