# Generated by Django 5.2.7 on 2026-01-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_propriedade_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
