# Generated by Django 5.2.7 on 2026-01-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_alter_endereco_numero_alter_endereco_rua'),
    ]

    operations = [
        migrations.AddField(
            model_name='amostra',
            name='smp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
