# Generated by Django 5.2.7 on 2026-01-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_amostra_smp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='laudos/pdf/'),
        ),
    ]
