# Generated by Django 5.2.7 on 2026-02-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_propriedade_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laudo',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
