# Generated by Django 5.2.5 on 2025-08-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='address.address')),
            ],
        ),
    ]
