import { gray, white, lightGray, black, green } from "../../config/colors.js";

export const styles = {
  container: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    backgroundColor: gray,
    color: black,
    fontFamily: "Poppins, sans-serif",
  },
  box: {
    backgroundColor: white,
    padding: "30px",
    borderRadius: "8px",
    textAlign: "center",
    width: "100%",
    maxWidth: "400px",
    boxShadow: "0 5px 10px 0 rgba(0, 0, 0, 0.10)",
  },
  mobileBox: {
    boxShadow: "none",
    borderRadius: "0",
    backgroundColor: "transparent",
  },
  button: {
    width: "60%",
    padding: "10px",
    backgroundColor: green,
    color: white,
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontWeight: 600,
    fontFamily: "Poppins, sans-serif",
    marginTop: "15px",
  },
  secondaryButton: {
    width: "60%",
    padding: "10px",
    backgroundColor: "transparent",
    color: green,
    border: `2px solid ${green}`,
    borderRadius: "4px",
    cursor: "pointer",
    fontWeight: 600,
    fontFamily: "Poppins, sans-serif",
    marginTop: "10px",
  },
  alertBox: {
    backgroundColor: "#fff3cd",
    border: "1px solid #ffc107",
    borderRadius: "4px",
    padding: "12px",
    marginBottom: "16px",
    fontSize: "0.9rem",
    color: "#856404",
    textAlign: "left",
    fontFamily: "Poppins, sans-serif",
  },
  message: {
    marginTop: "16px",
    padding: "10px",
    borderRadius: "4px",
    fontWeight: 600,
    fontSize: "0.9rem",
    fontFamily: "Poppins, sans-serif",
  },
  messageSuccess: {
    color: "#155724",
    backgroundColor: "#d4edda",
    border: "1px solid #c3e6cb",
  },
  messageError: {
    fontFamily: "Poppins, sans-serif",
    color: "#d32f2f", /* Vermelho */
    fontSize: "17px",
    textAlign: "center",
    minHeight: "20px",
    fontWeight: 500,
    padding: "8px",
    width: "100%",
  },
};